webtalk_init -webtalk_dir C:/Users/asvam/vivado projects/encoder_8x1_priority/encoder_8x1_priority.sim/sim_1/behav/xsim/xsim.dir/encoder_8x1_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 21 22:58:52 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0fcbd1f0-73a4-452f-a9d3-60d5bbf1f39f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "05275cfb6c3d410d841e747d1dc854cb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "180 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7268_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3726957797 -regid "" -xml C:/Users/asvam/vivado projects/encoder_8x1_priority/encoder_8x1_priority.sim/sim_1/behav/xsim/xsim.dir/encoder_8x1_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/asvam/vivado projects/encoder_8x1_priority/encoder_8x1_priority.sim/sim_1/behav/xsim/xsim.dir/encoder_8x1_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/asvam/vivado projects/encoder_8x1_priority/encoder_8x1_priority.sim/sim_1/behav/xsim/xsim.dir/encoder_8x1_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
