set_property SRC_FILE_INFO {cfile:{C:/Users/asvam/vivado projects/One_Hot_State_Encoding_Moore_Sequence_Detector/One_Hot_State_Encoding_Moore_Sequence_Detector.srcs/constrs_1/new/one_hot_moore_seq_det_xdc.xdc} rfile:../../../One_Hot_State_Encoding_Moore_Sequence_Detector.srcs/constrs_1/new/one_hot_moore_seq_det_xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports in_seq]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports out_detect]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports rst]
