set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports q]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property PACKAGE_PIN V17 [get_ports en]
set_property PACKAGE_PIN L1 [get_ports q]
set_property PACKAGE_PIN R2 [get_ports d]
set_property PACKAGE_PIN T1 [get_ports rstn]
